{"uuid": "66503827-a5ea-401c-82ea-c42c4418619a", "children": ["b59d1014-2430-47e4-947f-802aecfd860a"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=98.0.4758.102)\n\n", "trace": "  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ajayb\\PycharmProjects\\PageObjectModelFramework\\PageObjectModelFramework\\Testcases\\conftest.py\", line 36, in get_browser\n    driver.maximize_window()\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1645108777392, "stop": 1645108798322}], "start": 1645108777392, "stop": 1645108798384}