{"uuid": "93fdc50d-b040-4b83-a501-f5fde741f3e0", "children": ["52628d10-07b8-4b7b-add8-9948f008cb77"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=98.0.4758.102)\n\n", "trace": "  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ajayb\\PycharmProjects\\PageObjectModelFramework\\PageObjectModelFramework\\Testcases\\conftest.py\", line 36, in get_browser\n    driver.maximize_window()\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\ajayb\\pycharmprojects\\pageobjectmodelframework\\pageobjectmodelframework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1645108763217, "stop": 1645108777319}], "start": 1645108763217, "stop": 1645108777378}